define({
  "name": "关系维护",
  "version": "1.0.0",
  "description": "api接口文档",
  "title": "关系维护-api接口文档",
  "url": "http://test.relationkeep.cn",
  "order": [
    "group_example",
    "group_user",
    "group_customer",
    "example",
    "user_user_initialize",
    "user_user_bindWxPhone",
    "user_user_login",
    "msg_phoneMsg_sendRegister",
    "user_user_register",
    "msg_phoneMsg_sendRetrievePwd",
    "user_user_retrievePwd",
    "user_user_uploadHeadPic",
    "user_user_updateHeadPic",
    "user_user_updateNickName",
    "msg_phoneMsg_sendUpdatePhone",
    "user_user_updatePhone",
    "user_user_get",
    "user_hobby_config",
    "user_hobby_get",
    "user_hobby_update",
    "user_job_config",
    "user_job_get",
    "user_job_update",
    "user_remind_list",
    "customer_customer_config",
    "customer_customer_list",
    "customer_customer_get",
    "customer_customer_save",
    "customer_customer_update",
    "customer_customer_delete",
    "customer_customer_uploadHeadPic",
    "customer_customer_updateHeadPic",
    "customer_family_config",
    "customer_family_list",
    "customer_family_get",
    "customer_family_save",
    "customer_family_update",
    "customer_family_delete",
    "customer_hobby_config",
    "customer_hobby_get",
    "customer_hobby_update",
    "customer_job_config",
    "customer_job_get",
    "customer_job_update",
    "customer_memorialDay_config",
    "customer_memorialDay_list",
    "customer_memorialDay_get",
    "customer_memorialDay_save",
    "customer_memorialDay_update",
    "customer_memorialDay_delete",
    "customer_problem_config",
    "customer_problem_get",
    "customer_problem_update",
    "customer_relation_config",
    "customer_relation_get",
    "customer_relation_update",
    "customer_maintain_config",
    "customer_maintain_get",
    "customer_maintain_update",
    "customer_detail_get",
    "customer_detail_update"
  ],
  "sampleUrl": false,
  "defaultVersion": "0.0.0",
  "apidoc": "0.3.0",
  "generator": {
    "name": "apidoc",
    "time": "2019-01-02T09:53:03.688Z",
    "url": "http://apidocjs.com",
    "version": "0.17.7"
  }
});
